package com.efhem.boardgame;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author fadegbite
 */
public class App extends javax.swing.JFrame {

    private final BoardGame boardGame;
    JButton[][] gameButtons = new JButton[8][8];

    static final int ROWCOL = 8;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        boardGame = new BoardGame();
        initGameButton();
    }

    private void initGameButton() {
        gameButtons[0][0] = jButton1;
        gameButtons[0][1] = jButton2;
        gameButtons[0][2] = jButton3;
        gameButtons[0][3] = jButton4;
        gameButtons[0][4] = jButton5;
        gameButtons[0][5] = jButton6;
        gameButtons[0][6] = jButton7;
        gameButtons[0][7] = jButton8;

        gameButtons[1][0] = jButton9;
        gameButtons[1][1] = jButton10;
        gameButtons[1][2] = jButton11;
        gameButtons[1][3] = jButton12;
        gameButtons[1][4] = jButton13;
        gameButtons[1][5] = jButton14;
        gameButtons[1][6] = jButton15;
        gameButtons[1][7] = jButton16;

        gameButtons[2][0] = jButton17;
        gameButtons[2][1] = jButton18;
        gameButtons[2][2] = jButton19;
        gameButtons[2][3] = jButton20;
        gameButtons[2][4] = jButton21;
        gameButtons[2][5] = jButton22;
        gameButtons[2][6] = jButton23;
        gameButtons[2][7] = jButton24;

        gameButtons[3][0] = jButton25;
        gameButtons[3][1] = jButton26;
        gameButtons[3][2] = jButton27;
        gameButtons[3][3] = jButton28;
        gameButtons[3][4] = jButton29;
        gameButtons[3][5] = jButton30;
        gameButtons[3][6] = jButton31;
        gameButtons[3][7] = jButton32;

        gameButtons[4][0] = jButton33;
        gameButtons[4][1] = jButton34;
        gameButtons[4][2] = jButton35;
        gameButtons[4][3] = jButton36;
        gameButtons[4][4] = jButton37;
        gameButtons[4][5] = jButton38;
        gameButtons[4][6] = jButton39;
        gameButtons[4][7] = jButton40;

        gameButtons[5][0] = jButton41;
        gameButtons[5][1] = jButton42;
        gameButtons[5][2] = jButton43;
        gameButtons[5][3] = jButton44;
        gameButtons[5][4] = jButton45;
        gameButtons[5][5] = jButton46;
        gameButtons[5][6] = jButton47;
        gameButtons[5][7] = jButton48;

        gameButtons[6][0] = jButton49;
        gameButtons[6][1] = jButton50;
        gameButtons[6][2] = jButton51;
        gameButtons[6][3] = jButton52;
        gameButtons[6][4] = jButton53;
        gameButtons[6][5] = jButton54;
        gameButtons[6][6] = jButton55;
        gameButtons[6][7] = jButton56;

        gameButtons[7][0] = jButton57;
        gameButtons[7][1] = jButton58;
        gameButtons[7][2] = jButton59;
        gameButtons[7][3] = jButton60;
        gameButtons[7][4] = jButton61;
        gameButtons[7][5] = jButton62;
        gameButtons[7][6] = jButton63;
        gameButtons[7][7] = jButton64;

        setEnableBoardButton(false);
        setEnableStartButton();
    }

    private void setEnableBoardButton(boolean enable) {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                JButton button = gameButtons[i][j];
                button.setText(null);
                button.setEnabled(enable);
                if (!enable) {
                    button.setBackground(null);
                }
            }
        }
    }

    private void boardButtonaddActionListener() {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                JButton button = gameButtons[i][j];
                button.addActionListener((evt) -> {
                    boardButtonActionPerformed(evt);
                });
            }
        }
    }

    private void boardButtonremoveAllActionListener() {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                JButton button = gameButtons[i][j];
                removeActionListener(button);
            }
        }
    }

    private void removeActionListener(JButton button) {
        for (ActionListener listener : button.getActionListeners()) {
            button.removeActionListener(listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        boardBar = new javax.swing.JPanel();
        startButtonContainer = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        buttonsContainer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        playerBar.setLayout(new java.awt.GridLayout(2, 3, 0, 1));

        jLabel1.setText("Player 1");
        playerBar.add(jLabel1);

        jLabel2.setText("Player 2");
        playerBar.add(jLabel2);

        jLabel3.setText("Player 3");
        playerBar.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Blue", "Black" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        playerBar.add(jComboBox1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Blue", "Black" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        playerBar.add(jComboBox2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Blue", "Black" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        playerBar.add(jComboBox3);

        getContentPane().add(playerBar, java.awt.BorderLayout.NORTH);

        boardBar.setLayout(new java.awt.BorderLayout(0, 2));

        startButtonContainer.setPreferredSize(new java.awt.Dimension(96, 30));

        startButton.setText("Start Game");
        startButton.setPreferredSize(new java.awt.Dimension(640, 30));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startButtonContainerLayout = new javax.swing.GroupLayout(startButtonContainer);
        startButtonContainer.setLayout(startButtonContainerLayout);
        startButtonContainerLayout.setHorizontalGroup(
            startButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        startButtonContainerLayout.setVerticalGroup(
            startButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startButtonContainerLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(482, 482, 482))
        );

        boardBar.add(startButtonContainer, java.awt.BorderLayout.NORTH);

        buttonsContainer.setMinimumSize(new java.awt.Dimension(640, 300));
        buttonsContainer.setPreferredSize(new java.awt.Dimension(640, 380));
        buttonsContainer.setLayout(new java.awt.GridLayout(8, 8, 1, 1));

        jButton1.setText("jButton1");
        buttonsContainer.add(jButton1);

        jButton2.setText("jButton2");
        buttonsContainer.add(jButton2);

        jButton3.setText("jButton3");
        buttonsContainer.add(jButton3);

        jButton4.setText("jButton4");
        buttonsContainer.add(jButton4);

        jButton5.setText("jButton5");
        buttonsContainer.add(jButton5);

        jButton6.setText("jButton6");
        buttonsContainer.add(jButton6);

        jButton7.setText("jButton7");
        buttonsContainer.add(jButton7);

        jButton8.setText("jButton8");
        buttonsContainer.add(jButton8);

        jButton9.setText("jButton9");
        buttonsContainer.add(jButton9);

        jButton10.setText("jButton10");
        buttonsContainer.add(jButton10);

        jButton11.setText("jButton11");
        buttonsContainer.add(jButton11);

        jButton12.setText("jButton12");
        buttonsContainer.add(jButton12);

        jButton13.setText("jButton13");
        buttonsContainer.add(jButton13);

        jButton14.setText("jButton14");
        buttonsContainer.add(jButton14);

        jButton15.setText("jButton15");
        buttonsContainer.add(jButton15);

        jButton16.setText("jButton16");
        buttonsContainer.add(jButton16);

        jButton17.setText("jButton17");
        buttonsContainer.add(jButton17);

        jButton18.setText("jButton18");
        buttonsContainer.add(jButton18);

        jButton19.setText("jButton19");
        buttonsContainer.add(jButton19);

        jButton20.setText("jButton20");
        buttonsContainer.add(jButton20);

        jButton21.setText("jButton21");
        buttonsContainer.add(jButton21);

        jButton22.setText("jButton22");
        buttonsContainer.add(jButton22);

        jButton23.setText("jButton23");
        buttonsContainer.add(jButton23);

        jButton24.setText("jButton24");
        buttonsContainer.add(jButton24);

        jButton25.setText("jButton25");
        buttonsContainer.add(jButton25);

        jButton26.setText("jButton26");
        buttonsContainer.add(jButton26);

        jButton27.setText("jButton27");
        buttonsContainer.add(jButton27);

        jButton28.setText("jButton28");
        buttonsContainer.add(jButton28);

        jButton29.setText("jButton29");
        buttonsContainer.add(jButton29);

        jButton30.setText("jButton30");
        buttonsContainer.add(jButton30);

        jButton31.setText("jButton31");
        buttonsContainer.add(jButton31);

        jButton32.setText("jButton32");
        buttonsContainer.add(jButton32);

        jButton33.setText("jButton33");
        buttonsContainer.add(jButton33);

        jButton34.setText("jButton34");
        buttonsContainer.add(jButton34);

        jButton35.setText("jButton35");
        buttonsContainer.add(jButton35);

        jButton36.setText("jButton36");
        buttonsContainer.add(jButton36);

        jButton37.setText("jButton37");
        buttonsContainer.add(jButton37);

        jButton38.setText("jButton38");
        buttonsContainer.add(jButton38);

        jButton39.setText("jButton39");
        buttonsContainer.add(jButton39);

        jButton40.setText("jButton40");
        buttonsContainer.add(jButton40);

        jButton41.setText("jButton41");
        buttonsContainer.add(jButton41);

        jButton42.setText("jButton42");
        buttonsContainer.add(jButton42);

        jButton43.setText("jButton43");
        buttonsContainer.add(jButton43);

        jButton44.setText("jButton44");
        buttonsContainer.add(jButton44);

        jButton45.setText("jButton45");
        buttonsContainer.add(jButton45);

        jButton46.setText("jButton46");
        buttonsContainer.add(jButton46);

        jButton47.setText("jButton47");
        buttonsContainer.add(jButton47);

        jButton48.setText("jButton48");
        buttonsContainer.add(jButton48);

        jButton49.setText("jButton49");
        buttonsContainer.add(jButton49);

        jButton50.setText("jButton50");
        buttonsContainer.add(jButton50);

        jButton51.setText("jButton51");
        buttonsContainer.add(jButton51);

        jButton52.setText("jButton52");
        buttonsContainer.add(jButton52);

        jButton53.setText("jButton53");
        buttonsContainer.add(jButton53);

        jButton54.setText("jButton54");
        buttonsContainer.add(jButton54);

        jButton55.setText("jButton55");
        buttonsContainer.add(jButton55);

        jButton56.setText("jButton56");
        buttonsContainer.add(jButton56);

        jButton57.setText("jButton57");
        buttonsContainer.add(jButton57);

        jButton58.setText("jButton58");
        buttonsContainer.add(jButton58);

        jButton59.setText("jButton59");
        buttonsContainer.add(jButton59);

        jButton60.setText("jButton60");
        buttonsContainer.add(jButton60);

        jButton61.setText("jButton61");
        buttonsContainer.add(jButton61);

        jButton62.setText("jButton62");
        buttonsContainer.add(jButton62);

        jButton63.setText("jButton63");
        buttonsContainer.add(jButton63);

        jButton64.setText("jButton64");
        buttonsContainer.add(jButton64);

        boardBar.add(buttonsContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(boardBar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startGame();
    }//GEN-LAST:event_startButtonActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        boardGame.setPlayer2Color(getSelectedItem(evt));
        setEnableStartButton();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        boardGame.setPlayer1Color(getSelectedItem(evt));
        setEnableStartButton();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        boardGame.setPlayer3Color(getSelectedItem(evt));
        setEnableStartButton();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    private void boardButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JButton thisOne = (JButton) evt.getSource();
        removeActionListener(thisOne);
        Player player = boardGame.getPlayerTurn();

        System.out.println("Setting button color");
        System.out.println(player);

        thisOne.setBackground(player.getColor());

        boardGame.setNextPlayerTurn();
        setPlayerTurnIndicator(true);

        checkForWin(player);
    }

    private void setPlayerTurnIndicator(boolean playing) {
        if (playing) {
            Player player = boardGame.getPlayerTurn();
            System.out.println("Setting indicator");
            System.out.println(player);
            switch (player.getNumber()) {
                case 1 -> {
                    jLabel1.setOpaque(true);
                    jLabel1.setBackground(player.getColor());
                    jLabel2.setBackground(null);
                    jLabel3.setBackground(null);
                }
                case 2 -> {
                    jLabel2.setOpaque(true);
                    jLabel2.setBackground(player.getColor());
                    jLabel1.setBackground(null);
                    jLabel3.setBackground(null);
                }
                default -> {
                    jLabel3.setOpaque(true);
                    jLabel3.setBackground(player.getColor());
                    jLabel1.setBackground(null);
                    jLabel2.setBackground(null);
                }
            }
        } else {
            System.out.println("clear all indicator");
            jLabel1.setOpaque(false);
            jLabel2.setOpaque(false);
            jLabel3.setOpaque(false);
            jLabel1.setBackground(null);
            jLabel2.setBackground(null);
            jLabel3.setBackground(null);
        }
    }

    private void setEnableStartButton() {
        if (boardGame.arePlayerReady()) {
            startButton.setEnabled(true);
        } else {
            startButton.setEnabled(false);
        }
    }

    private void setEnablePlayerChoice(boolean enable) {
        jComboBox1.setEnabled(enable);
        jComboBox2.setEnabled(enable);
        jComboBox3.setEnabled(enable);
    }

    String getSelectedItem(java.awt.event.ActionEvent evt) {
        JComboBox comboBox = (JComboBox) evt.getSource();
        return String.valueOf(comboBox.getSelectedItem());
    }

    private void checkForWin(Player player) {
        String board = "";

        for (int row = 0; row < ROWCOL; row++) {
            for (int col = 0; col < ROWCOL; col++) {
                board += colorToChar(gameButtons[row][col].getBackground());
            }
            board += ".";
        }

        for (int col = 0; col < ROWCOL; col++) {
            for (int row = 0; row < ROWCOL; row++) {
                board += colorToChar(gameButtons[row][col].getBackground());
            }
            board += ".";
        }

        // Search diagonally from top-left to bottom-right
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                int row = i;
                int col = j;
                while (row < 8 && col < 8) {
                    board += colorToChar(gameButtons[row][col].getBackground());
                    row++;
                    col++;
                }
                board += ".";

            }
        }

        // Search diagonally from top-right to bottom-left
        for (int i = 0; i < 8; i++) {
            for (int j = 7; j >= 0; j--) {
                int row = i;
                int col = j;
                while (row < 8 && col >= 0) {
                    board += colorToChar(gameButtons[row][col].getBackground());
                    row++;
                    col--;
                }
                board += ".";
            }
        }

        if (board.contains("RRRR")) {
            JOptionPane.showMessageDialog(this, player.getName() + " have a winner");
            startGame();
        }

        if (board.contains("GGGG")) {

            JOptionPane.showMessageDialog(this, player.getName() + " have a winner");
            startGame();
        }

        if (board.contains("BBBB")) {

            JOptionPane.showMessageDialog(this, player.getName() + " have a winner");
            startGame();
        }

        if (board.contains("LLLL")) {

            JOptionPane.showMessageDialog(this, player.getName() + " have a winner");
            startGame();
        }

//        if (board.length() == 160) {
//            startGame();
//        }
          System.out.println("board size "+ board.length());

    }

    private String colorToChar(Color color) {
        String col;
        if (color == Color.RED) {
            col = "R";
        } else if (color == Color.GREEN) {
            col = "G";
        } else if (color == Color.BLUE) {
            col = "B";
        } else if (color == Color.BLACK) {
            col = "L";
        } else {
            col = "";
        }
        return col;
    }

    //Start game locks the choice components(JComboBox) until game is cancelled
    void startGame() {
        if (!boardGame.isCurrentlyPlaying()) {
            //playing
            setEnableBoardButton(true);
            setEnablePlayerChoice(false);
            boardButtonaddActionListener();
            boardGame.startedGame(true);
            startButton.setText("Cancel");
            setPlayerTurnIndicator(true);
        } else {
            //cancelling
            setEnableBoardButton(false);
            setEnablePlayerChoice(true);
            boardButtonremoveAllActionListener();
            startButton.setText("Start");

            boardGame.startedGame(false);
            setPlayerTurnIndicator(false);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardBar;
    private javax.swing.JPanel buttonsContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel playerBar;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startButtonContainer;
    // End of variables declaration//GEN-END:variables
}
